### PR TITLE
feat(nova-4): add nova 4 support

### LINKED ISSUE #8: Support for Laravel Nova 4.x
closed by https://github.com/dcasia/custom-relationship-field/pull/11

### PR DESCRIPTION
**Pull request by chrillep**
closes #8 

feel free to change, fix or do whatever as long as we get nova 4 support :)

### CODE REVIEW

**Comment by chrillep** [comment]
@qwertywelch @milewski @littlemiaor hello :)

**Comment by milewski** [comment]
Hi @chrillep , 

Thanks for the PR, I just tested it locally, but it doesn't seem to be working, the issue seems to be on the vue files, the request `interceptors` part is not working

**Comment by chrillep** [comment]
hmm yeah im to noob at that
but you mean

https://github.com/dcasia/custom-relationship-field/pull/9/files#diff-3d222dbb9a31339a71bc2417e768b375ac6c1ca841a90ce9d16d613e4aa22ae8R42-R63


ill have a look if i can fix it. possible sollutions are welcome

ref:
https://nova.laravel.com/docs/4.0/customization/frontend.html#event-bus

**Comment by milewski** [comment]
> but you mean
https://github.com/dcasia/custom-relationship-field/pull/9/files#diff-3d222dbb9a31339a71bc2417e768b375ac6c1ca841a90ce9d16d613e4aa22ae8R42-R63

Correct, I was seeing the source code of nova4, and seems that every time Nova.request() is called a new `axios.create()` is called... if that's the case it won't possible to inject global interceptors... so i think only solution might be to monkey-patch nova request function... something like this:

```js
const original = Nova.request

let axiosInstance = null

Nova.request = function (...params) {

  if(axiosInstance === null) {
    axiosInstance = original(...params)
  }

  return axiosInstance

}

then... 

beforeCreate() {
   axiosInstance.request.inperceptors.use(...)
}
```

This way axios.create() is only called once.. and then any interceptors will be present on any nova request.. not sure if this will break anything (possibly with other packages)... but I dont see another way around it...

**Comment by chrillep** [comment]
Hmm yeah as long as the originally added interceptors are there should be fine 


https://nova.laravel.com/docs/4.0/customization/frontend.html#nova-requests

Maybe look into partial clone of Axios or url based config.

That way it wouldn't break other addons

**Comment by milewski** [comment]
Hi @chrillep, I figured it out, and got it working in nova-4.. can you unprotect your fork master branch and enable the maintainer to edit this PR, I'm unable to push due to these settings... 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Comment by chrillep** [comment]
> Hi @chrillep, I figured it out, and got it working in nova-4.. can you unprotect your fork master branch and enable the maintainer to edit this PR, I'm unable to push due to these settings...
> 
> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

yay. yes sure

**Comment by chrillep** [comment]
sigh cant find it since we are an org ...
Skärmavbild 2022-11-15 kl  10 39 13

**Comment by chrillep** [comment]
ok so https://github.com/orgs/community/discussions/5634 ...
ill transfer this to my personal account then and try again

**Comment by chrillep** [comment]
ill transfer this to my personal account then

**Comment by milewski** [comment]
Well, its okay then I can create a new PR based on this .. no worries

**Comment by chrillep** [comment]
there now 
Skärmavbild 2022-11-15 kl  10 44 27
ok to fast so nvm :) closing this

**Pull request closed without merging**
